import {
  FrontierBarChart3Icon,
  FrontierCalculatorIcon,
  FrontierClipboardCheckIcon,
  FrontierCopyIcon,
  FrontierCreditCardIcon,
  FrontierDollarSignIcon,
  FrontierFolderTreeIcon,
  FrontierHandshakeIcon,
  FrontierHelpCircleIcon,
  FrontierLayoutDashboardIcon,
  FrontierLayoutGridIcon,
  FrontierLink2Icon,
  FrontierLogOutIcon,
  FrontierMailIcon,
  FrontierMenuIcon,
  FrontierMessageSquareIcon,
  FrontierPackageIcon,
  FrontierPackagePlusIcon,
  FrontierSendIcon,
  FrontierSettingsIcon,
  FrontierSearchIcon,
  FrontierShieldIcon,
  FrontierShoppingBagIcon,
  FrontierStoreIcon,
  FrontierUploadIcon,
  FrontierUserIcon,
  FrontierUserPlusIcon,
  FrontierUsersIcon,
  FrontierUsersRoundIcon,
  FrontierWalletIcon,
  FrontierWarehouseIcon,
} from "@/components/icons/frontier";
import { createFrontierAssetIcon, createFrontierBrandIcon } from "@/components/icons/frontier/FrontierAssetIcon";

/** Sidebar nav icons — brand PNG assets with code SVG fallbacks */
export const frontierSidebarIcons = {
  layoutDashboard: createFrontierAssetIcon(
    "layoutDashboard",
    FrontierLayoutDashboardIcon,
    "FrontierSidebarLayoutDashboardIcon",
  ),
  layoutGrid: createFrontierAssetIcon(
    "layoutGrid",
    FrontierLayoutGridIcon,
    "FrontierSidebarLayoutGridIcon",
  ),
  clipboardCheck: createFrontierAssetIcon(
    "clipboardCheck",
    FrontierClipboardCheckIcon,
    "FrontierSidebarClipboardCheckIcon",
  ),
  users: createFrontierAssetIcon("users", FrontierUsersIcon, "FrontierSidebarUsersIcon"),
  usersRound: createFrontierAssetIcon(
    "usersRound",
    FrontierUsersRoundIcon,
    "FrontierSidebarUsersRoundIcon",
  ),
  user: createFrontierAssetIcon("user", FrontierUserIcon, "FrontierSidebarUserIcon"),
  userPlus: createFrontierAssetIcon(
    "userPlus",
    FrontierUserPlusIcon,
    "FrontierSidebarUserPlusIcon",
  ),
  package: createFrontierAssetIcon("package", FrontierPackageIcon, "FrontierSidebarPackageIcon"),
  shoppingBag: createFrontierAssetIcon(
    "shoppingBag",
    FrontierShoppingBagIcon,
    "FrontierSidebarShoppingBagIcon",
  ),
  wallet: createFrontierAssetIcon("wallet", FrontierWalletIcon, "FrontierSidebarWalletIcon"),
  handshake: createFrontierAssetIcon(
    "handshake",
    FrontierHandshakeIcon,
    "FrontierSidebarHandshakeIcon",
  ),
  warehouse: createFrontierAssetIcon(
    "warehouse",
    FrontierWarehouseIcon,
    "FrontierSidebarWarehouseIcon",
  ),
  barChart: createFrontierAssetIcon(
    "barChart",
    FrontierBarChart3Icon,
    "FrontierSidebarBarChartIcon",
  ),
  shield: createFrontierAssetIcon("shield", FrontierShieldIcon, "FrontierSidebarShieldIcon"),
  settings: createFrontierAssetIcon(
    "settings",
    FrontierSettingsIcon,
    "FrontierSidebarSettingsIcon",
  ),
  store: createFrontierAssetIcon("store", FrontierStoreIcon, "FrontierSidebarStoreIcon"),
  calculator: createFrontierAssetIcon(
    "calculator",
    FrontierCalculatorIcon,
    "FrontierSidebarCalculatorIcon",
  ),
  messageSquare: createFrontierAssetIcon(
    "messageSquare",
    FrontierMessageSquareIcon,
    "FrontierSidebarMessageSquareIcon",
  ),
  helpCircle: createFrontierAssetIcon(
    "helpCircle",
    FrontierHelpCircleIcon,
    "FrontierSidebarHelpCircleIcon",
  ),
  logOut: createFrontierAssetIcon("logOut", FrontierLogOutIcon, "FrontierSidebarLogOutIcon"),
  menu: createFrontierAssetIcon("menu", FrontierMenuIcon, "FrontierSidebarMenuIcon"),
} as const;

/** Dashboard section / toolbar brand PNG icons */
export const frontierBrandIcons = {
  mail: createFrontierBrandIcon("mail", FrontierMailIcon, "FrontierBrandMailIcon"),
  search: createFrontierBrandIcon("search", FrontierSearchIcon, "FrontierBrandSearchIcon"),
  pieChart: createFrontierBrandIcon("pieChart", FrontierBarChart3Icon, "FrontierBrandPieChartIcon"),
  wallet: createFrontierBrandIcon("wallet", FrontierWalletIcon, "FrontierBrandWalletIcon"),
  home: createFrontierBrandIcon("home", FrontierStoreIcon, "FrontierBrandHomeIcon"),
  cards: createFrontierBrandIcon("cards", FrontierCopyIcon, "FrontierBrandCardsIcon"),
  forward: createFrontierBrandIcon("forward", FrontierSendIcon, "FrontierBrandForwardIcon"),
  location: createFrontierBrandIcon("location", FrontierLink2Icon, "FrontierBrandLocationIcon"),
  folder: createFrontierBrandIcon("folder", FrontierFolderTreeIcon, "FrontierBrandFolderIcon"),
  add: createFrontierBrandIcon("add", FrontierUploadIcon, "FrontierBrandAddIcon"),
  headset: createFrontierBrandIcon("headset", FrontierHelpCircleIcon, "FrontierBrandHeadsetIcon"),
  notification: createFrontierBrandIcon(
    "notification",
    FrontierUsersIcon,
    "FrontierBrandNotificationIcon",
  ),
  user: createFrontierBrandIcon("user", FrontierUserIcon, "FrontierBrandUserIcon"),
  grid: createFrontierBrandIcon("grid", FrontierLayoutGridIcon, "FrontierBrandGridIcon"),
  priceTag: createFrontierBrandIcon(
    "priceTag",
    FrontierShoppingBagIcon,
    "FrontierBrandPriceTagIcon",
  ),
  package: createFrontierBrandIcon("cards", FrontierPackageIcon, "FrontierBrandPackageIcon"),
  packagePlus: createFrontierBrandIcon(
    "add",
    FrontierPackagePlusIcon,
    "FrontierBrandPackagePlusIcon",
  ),
  dollarSign: createFrontierBrandIcon(
    "priceTag",
    FrontierDollarSignIcon,
    "FrontierBrandDollarSignIcon",
  ),
  warehouse: createFrontierBrandIcon(
    "folder",
    FrontierWarehouseIcon,
    "FrontierBrandWarehouseIcon",
  ),
  analytics: createFrontierBrandIcon(
    "analytics",
    FrontierHandshakeIcon,
    "FrontierBrandAnalyticsIcon",
  ),
} as const;
